config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :permissions
  resources :roles
  resources :clients do
    member do
      get :summary
    end
  end

  resources :payment_credentials, except: [:show, :destroy]

  namespace :mp do
    get :success, to: "feedback#success"
    get :failure, to: "feedback#failure"
    get :pending, to: "feedback#pending"
    post 'webhook', to: 'notifications#webhook'

  end
  resources :loans

  resources :payments

  resources :collections

  resources :third_party_types
  resources :expense_types
  resources :statuses
  resources :payment_terms
  resources :reasons
  resources :tracks
  resources :section_permissions
  resources :users do
    collection do
      get :hierarchy
    end
  end
  resources :permission_roles, only: [:index, :create, :update]

  namespace :api do
    resources :clients, only: [:index, :show, :create, :update]
    resources :expenses, only: [:index, :show, :create, :update]
    resources :expense_types, only: [:index]
    resources :payment_terms, only: [:index]
    resources :loans, only: [:index, :show, :create, :update]
    resources :payments, only: [:index, :show, :create, :update]
    resource :session, only: [:create, :destroy]
    
  end

  namespace :api do
    namespace :client do
      resource :session, only: [:create, :destroy]
      resources :loans, only: [:index, :show]
    end
  end

  namespace :admin do
    post "loans/recalc", to: "loans#recalc"
  end

  resources :reports, only: [] do
    collection do
      get :loans
      get :collections_progress
      get :payments
      get :settlements
    end
  end

  resources :hierarchy, only: [] do
    member do
      get :partners
      get :collectors
      get :collections
    end
  end

  resources :settlements do
    member do
      post :recalculate
      post :close
    end

    resources :settlement_topups, only: [:create, :destroy]
    resources :settlement_withdrawals, only: [:create, :destroy]
    resources :expenses, only: [:create, :destroy]
  end
  

  resources :user_sessions, only: [:new, :create]
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'login', to: 'user_sessions#new', as: :login

  # Ruta por defecto
  root to: 'dashboards#clinic'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  get "dashboards/clinic"
  get "dashboards/index"
  get "dashboards/wallet"

  get "apps/calendar"
  get "apps/chat"
  get "apps/email"
  get "apps/file-manager", to: 'apps#file_manager'

  get "apps/invoice/create", to: 'apps#invoice_create'
  get "apps/invoice/details", to: 'apps#invoice_details'
  get "apps/invoice/list", to: 'apps#invoice_list'

  get "hospital/doctors/add", to: 'hospital#add_doctors'
  get "hospital/patients/add", to: 'hospital#add_patients'
  get "hospital/appointments", to: 'hospital#appointments'
  get "hospital/contacts", to: 'hospital#contacts'
  get "hospital/departments", to: 'hospital#departments'
  get "hospital/doctor/details", to: 'hospital#doctor_details'
  get "hospital/doctors", to: 'hospital#doctors'
  get "hospital/patient/details", to: 'hospital#patient_details'
  get "hospital/patients", to: 'hospital#patients'
  get "hospital/payments", to: 'hospital#payments'
  get "hospital/reviews", to: 'hospital#reviews'
  get "hospital/staffs", to: 'hospital#staffs'

  get "e-commerce/categories", to: 'e_commerce#categories'
  get "e-commerce/customers", to: 'e_commerce#customers'
  get "e-commerce/order/details", to: 'e_commerce#order_details'
  get "e-commerce/orders", to: 'e_commerce#orders'
  get "e-commerce/product/details", to: 'e_commerce#product_details'
  get "e-commerce/products", to: 'e_commerce#products'
  get "e-commerce/products/add", to: 'e_commerce#products_add'
  get "e-commerce/products/grid", to: 'e_commerce#products_grid'
  get "e-commerce/reviews", to: 'e_commerce#reviews'
  get "e-commerce/seller/details", to: 'e_commerce#seller_details'
  get "e-commerce/sellers", to: 'e_commerce#sellers'
  get "e-commerce/settings", to: 'e_commerce#settings'

  get "pages/coming-soon", to: 'pages#coming_soon'
  get "pages/faq"
  get "pages/maintenance"
  get "pages/pricing"
  get "pages/pricing-2", to: 'pages#pricing_2'
  get "pages/starter"
  get "pages/terms-conditions", to: 'pages#terms_conditions'
  get "pages/timeline"

  get "auth/2fa", to: 'auth#auth_2fa'
  get "auth/account-deactivation", to: 'auth#account_deactivation'
  get "auth/confirm-mail", to: 'auth#confirm_mail'
  get "auth/create-password", to: 'auth#create_password'
  get "auth/lock-screen", to: 'auth#lock_screen'
  get "auth/login", to: 'auth#login'
  get "auth/login-pin", to: 'auth#login_pin'
  get "auth/logout", to: 'auth#logout'
  get "auth/recover-password", to: 'auth#recover_password'
  get "auth/register", to: 'auth#register'

  get "error/400", to: 'error#error_400'
  get "error/401", to: 'error#error_401'
  get "error/403", to: 'error#error_403'
  get "error/404", to: 'error#error_404'
  get "error/404-alt", to: 'error#error_404_alt'
  get "error/408", to: 'error#error_408'
  get "error/500", to: 'error#error_500'
  get "error/501", to: 'error#error_501'
  get "error/502", to: 'error#error_502'
  get "error/service-unavailable", to: 'error#service_unavailable'

  get "email-templates/activation", to: 'email_templates#activation'
  get "email-templates/basic", to: 'email_templates#basic'
  get "email-templates/invoice", to: 'email_templates#invoice'

  get "layouts/compact", to: 'layouts_eg#compact'
  get "layouts/detached", to: 'layouts_eg#detached'
  get "layouts/full", to: 'layouts_eg#full'
  get "layouts/fullscreen", to: 'layouts_eg#fullscreen'
  get "layouts/horizontal", to: 'layouts_eg#horizontal'
  get "layouts/hover", to: 'layouts_eg#hover'
  get "layouts/icon-view", to: 'layouts_eg#icon_view'

  get "ui/accordions"
  get "ui/alerts"
  get "ui/avatars"
  get "ui/badges"
  get "ui/breadcrumb"
  get "ui/buttons"
  get "ui/cards"
  get "ui/carousel"
  get "ui/collapse"
  get "ui/dropdowns"
  get "ui/embed-video", to: 'ui#embed_video'
  get "ui/grid"
  get "ui/links"
  get "ui/list-group", to: 'ui#list_group'
  get "ui/modals"
  get "ui/notifications"
  get "ui/offcanvas"
  get "ui/pagination"
  get "ui/placeholders"
  get "ui/popovers"
  get "ui/progress"
  get "ui/ratios"
  get "ui/scrollspy"
  get "ui/spinners"
  get "ui/tabs"
  get "ui/tooltips"
  get "ui/typography"
  get "ui/utilities"

  get "extended/dragula"
  get "extended/ratings"
  get "extended/scrollbar"
  get "extended/sweet-alerts", to: "extended#sweet_alerts"

  get "icons/solar"
  get "icons/tabler"

  get "charts/area"
  get "charts/bar"
  get "charts/boxplot"
  get "charts/bubble"
  get "charts/candlestick"
  get "charts/column"
  get "charts/heatmap"
  get "charts/line"
  get "charts/mixed"
  get "charts/pie"
  get "charts/polar-area", to: "charts#polar_area"
  get "charts/radar"
  get "charts/radialbar"
  get "charts/scatter"
  get "charts/sparklines"
  get "charts/timeline"
  get "charts/treemap"

  get "forms/editors"
  get "forms/elements"
  get "forms/fileuploads"
  get "forms/inputmask"
  get "forms/layouts"
  get "forms/picker"
  get "forms/range-slider", to: "forms#range_slider"
  get "forms/select"
  get "forms/validation"
  get "forms/wizard"

  get "tables/basic"
  get "tables/gridjs"

  get "maps/google"
  get "maps/leaflet"
  get "maps/vector"
end

app/models/payment_term.rb
class PaymentTerm < ApplicationRecord
end

app/controllers/api/payment_terms_controller.rb
class Api::PaymentTermsController < Api::BaseController
  

  def index
    render json: PaymentTerm.all
  end
end

app/controllers/payment_terms_controller.rb
class PaymentTermsController < ApplicationController
    def index
        @payment_terms = PaymentTerm.all
    end
    
    def new
        @payment_term = PaymentTerm.new
        respond_to do |format|
            format.turbo_stream
        end
    end
    
    def edit
        @payment_term = PaymentTerm.find(params[:id])
        respond_to do |format|
            format.turbo_stream
        end
    end
    
    def create
        @payment_term = PaymentTerm.new(payment_term_params)
        if @payment_term.save
            redirect_to payment_terms_path, notice: "Modulo creada exitosamente"
        else
            render :new, status: :unprocessable_entity, formats: [:turbo_stream]
        end
    end
    
    def update
        @payment_term = PaymentTerm.find(params[:id])
        if @payment_term.update(payment_term_params)
            redirect_to payment_terms_path, notice: "Modulo actualizada exitosamente"
        else
            render :edit, status: :unprocessable_entity, formats: [:turbo_stream]
        end
    end
        
    private
        
    def payment_term_params
        params.require(:payment_term).permit(:percentage, :quota_days, :payment_frequency, :payment_days, :monthly)
    end

end

app/helpers/payment_terms_helper.rb
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<%= form_with model: payment_term, data: { turbo: false } do |f| %>
  <div class="mb-3">
    <%= f.label :percentage, "Porcentaje", class: "form-label" %>
    <%= f.number_field :percentage, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :quota_days, "Couta dias", class: "form-label" %>
    <%= f.number_field :quota_days, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :payment_frequency, "Frecuencia pago letras", class: "form-label" %>
    <%= f.text_field :payment_frequency, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :payment_days, "# dias pago", class: "form-label" %>
    <%= f.number_field :payment_days, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :monthly, "Mensual?", class: "form-label" %>
    <%= f.check_box :monthly %>
  </div>
  <div class="d-flex justify-content-end">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/payment_terms/_form_modal.html.erb
<!-- app/views/payment_terms/_form_modal.html.erb -->

<div class="modal fade show d-block" id="payment_termModal" tabindex="-1" style="background: rgba(0,0,0,0.5);" aria-modal="true" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= local_assigns[:title] || 'Ruta' %></h5>
        <button type="button" class="btn-close" data-action="click->modal#close" aria-label="Cerrar"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', payment_term: payment_term %>
      </div>
    </div>
  </div>
</div>
<script>
  document.querySelector('.btn-close').addEventListener('click', () => {
    const modal = document.getElementById('payment_termModal');
    if (modal) {
      modal.classList.remove('show', 'd-block');
      modal.classList.add('fade');
      modal.style.display = 'none';
    }
  });
</script>

app/views/payment_terms/_table.html.erb
<% payment_terms.each do |payment_term| %>
  
  <tr id="payment_term_<%= payment_term.id %>">
    <td><%= payment_term.percentage %></td>
    <td><%= payment_term.quota_days %></td>
    <td><%= payment_term.payment_frequency %></td>
    <td><%= payment_term.payment_days %></td>
    <td><%= payment_term.monthly %></td>
    <td class="text-center">
      <%= button_to edit_payment_term_path(payment_term, format: :turbo_stream), method: :get, form: { data: { turbo_frame: "modal" }, class: "d-inline" }, class: "btn btn-soft-success btn-icon btn-sm rounded-circle", title: "Editar Ruta" do %>
        <i class="ti ti-edit"></i>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/payment_terms/edit.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
    <!-- Limpia antes -->
<% end %>
<%= turbo_stream.append "modal" do %>
  <%= render "form_modal", payment_term: @payment_term, title: "Editar Ruta" %>
<% end %>

app/views/payment_terms/index.html.erb
<!-- app/views/payment_terms/index.html.erb -->

<div class="card-header d-flex align-items-center justify-content-between border-bottom border-light">
  <h4 class="header-title">Rutas</h4>
<%= button_to 'Nuevo Ruta', new_payment_term_path(format: :turbo_stream), method: :get, form: { data: { turbo_frame: "modal" } }, class: "btn btn-primary" %>
</div>

<div class="table-responsive">
  <table class="table table-nowrap mb-0">
    <thead class="bg-light-subtle">
      <tr>
        <th>Porcentaje</th>
        <th>Couta Dias</th>
        <th>Frecuencua pagos letra</th>
        <th>No dias pago</th>
        <th>Es mensual?</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
        <%= turbo_frame_tag "payment_terms_table" do %>
            <%= render "table", payment_terms: @payment_terms %>
        <% end %>
    </tbody>
  </table>
</div>

app/views/payment_terms/new.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
  ""  <!-- Limpia antes -->
<% end %>
<%= turbo_stream.append "modal" do %>
  <%= render "form_modal", payment_term: @payment_term, title: "Nuevo Ruta" %>
<% end %>